# gprof_to_cdash.py
#
# Parses gprof flat-profile output and prints one <CTestMeasurement> tag per
# function to stdout. Invoked from run_gprof_analysis.cmake (generated by
# Profiling.cmake), which forwards this output, via message(), to the stdout
# of a CTest test so that ctest_test()/ctest_submit() attach the measurements
# to that test's entry on CDash. See the CTest "Additional Test Measurements"
# documentation for the tag format.
#
# Usage: gprof_to_cdash.py <gprof_output.txt> [--top-n N]

import argparse
import re
import sys

HEADER_RE = re.compile(r'^\s*%\s+cumulative\s+self\s+self\s+total')


def parse_gprof(gprof_file):
    """Yields (function_name, self_seconds) pairs from a gprof flat profile."""
    in_flat_profile = False
    with open(gprof_file) as f:
        for line in f:
            if not in_flat_profile:
                if HEADER_RE.match(line):
                    in_flat_profile = True
                continue

            if not line.strip():
                break  # blank line marks the end of the flat-profile table

            # Columns: % time, cumulative seconds, self seconds,
            # [calls, self ms/call, total ms/call,] name. The last three are
            # omitted by gprof for functions that were never called, so the
            # function name is always the last field and self seconds is
            # always the third field.
            fields = line.split()
            if len(fields) < 4:
                continue
            try:
                self_seconds = float(fields[2])
            except ValueError:
                continue
            yield fields[-1], self_seconds


def xml_escape(text):
    return (text.replace('&', '&amp;')
                .replace('<', '&lt;')
                .replace('>', '&gt;')
                .replace('"', '&quot;'))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('gprof_output', help='Path to a gprof flat-profile text report')
    parser.add_argument('--top-n', type=int, default=0,
                         help='Report only the N hottest functions (0 = no limit)')
    args = parser.parse_args()

    measurements = [(name, secs) for name, secs in parse_gprof(args.gprof_output) if secs > 0]
    measurements.sort(key=lambda item: item[1], reverse=True)
    if args.top_n > 0:
        measurements = measurements[:args.top_n]

    for name, self_seconds in measurements:
        sys.stdout.write(
            f'<CTestMeasurement type="numeric/double" name="{xml_escape(name)}-self_seconds">'
            f'{self_seconds}</CTestMeasurement>\n'
        )


if __name__ == '__main__':
    main()
