# =============================================================================
# Profiling.cmake
# Unified profiling framework for CTest-defined tests.
#
# Supported back-ends : vtune | gprof | hpctoolkit
# Minimum CMake       : 3.12  (list(SUBLIST), string(MAKE_C_IDENTIFIER),
#                               cmake_parse_arguments as a built-in command)
#
# This module:
#   1. Appends the required compiler/linker flags for the chosen back-end.
#   2. Overrides add_test() so every CTest test has its profiling output
#      stored in a per-test directory, preventing artifact clobbering across
#      multiple tests that share the same binary.
# =============================================================================

# -----------------------------------------------------------------------------
# Options
# -----------------------------------------------------------------------------
option(ENABLE_PROFILING
    "Wrap every CTest test with a profiler and collect artifacts" OFF)

set(PROFILING_TOOL "gprof" CACHE STRING
    "Profiling back-end: gprof | hpctoolkit | vtune")
set_property(CACHE PROFILING_TOOL PROPERTY STRINGS gprof hpctoolkit vtune)

set(PROFILING_OUTPUT_DIR "${CMAKE_BINARY_DIR}/profiling-results" CACHE PATH
    "Root directory that receives per-test profiling artifacts")

option(PROFILING_ANALYSIS
    "Generate a human-readable profiling report" OFF)

# -----------------------------------------------------------------------------
# Early exit when profiling is disabled
# -----------------------------------------------------------------------------
if(NOT ENABLE_PROFILING)
    return()
endif()

# -----------------------------------------------------------------------------
# Validate tool selection
# -----------------------------------------------------------------------------
if(NOT PROFILING_TOOL MATCHES "^(vtune|gprof|hpctoolkit)$")
    message(FATAL_ERROR
        "Profiling.cmake: PROFILING_TOOL must be vtune, gprof, or hpctoolkit "
        "(got '${PROFILING_TOOL}').")
endif()


# -----------------------------------------------------------------------------
# Compiler / linker flags
# -----------------------------------------------------------------------------
# -g: always add debug symbols so profilers can resolve addresses back to
# source lines, including Fortran module-mangled names.
foreach(_prof_lang IN ITEMS C CXX Fortran)
    if(DEFINED CMAKE_${_prof_lang}_COMPILER)
        if(NOT CMAKE_${_prof_lang}_FLAGS MATCHES "(^| )-g( |$)")
            string(APPEND CMAKE_${_prof_lang}_FLAGS " -g")
        endif()
    endif()
endforeach()
unset(_prof_lang)

if(PROFILING_TOOL STREQUAL "gprof")
    # -pg must appear in both compile and link steps for every active language
    # so the profiling startup code is linked regardless of which compiler
    # driver acts as the linker.
    foreach(_prof_lang IN ITEMS C CXX Fortran)
        if(DEFINED CMAKE_${_prof_lang}_COMPILER)
            if(NOT CMAKE_${_prof_lang}_FLAGS MATCHES "(^| )-pg( |$)")
                string(APPEND CMAKE_${_prof_lang}_FLAGS " -pg")
            endif()
        endif()
    endforeach()
    unset(_prof_lang)
    if(NOT CMAKE_EXE_LINKER_FLAGS MATCHES "(^| )-pg( |$)")
        string(APPEND CMAKE_EXE_LINKER_FLAGS " -pg")
    endif()
    if(NOT CMAKE_SHARED_LINKER_FLAGS MATCHES "(^| )-pg( |$)")
        string(APPEND CMAKE_SHARED_LINKER_FLAGS " -pg")
    endif()

elseif(PROFILING_TOOL STREQUAL "hpctoolkit" OR PROFILING_TOOL STREQUAL "vtune")
    # -rdynamic makes dynamic symbols visible to hpcrun/hpcstruct and VTune.
    if(NOT CMAKE_EXE_LINKER_FLAGS MATCHES "(^| )-rdynamic( |$)")
        string(APPEND CMAKE_EXE_LINKER_FLAGS " -rdynamic")
    endif()
endif()

# Root output directory — created at configure time so it exists before tests run.
file(MAKE_DIRECTORY "${PROFILING_OUTPUT_DIR}")

# Write the gprof post-processing script once into the output directory.
# It is invoked at test time via: cmake -DEXE=<path> -DOUTDIR=<dir> -P <script>
if(PROFILING_TOOL STREQUAL "gprof" AND PROFILING_ANALYSIS)
    file(WRITE "${PROFILING_OUTPUT_DIR}/run_gprof_analysis.cmake" [=[
# run_gprof_analysis.cmake — generated by Profiling.cmake
# Parameters (via -D): EXE  absolute path to the instrumented executable
#                      OUTDIR  per-test profiling output directory
file(GLOB _gprof_gmon_files LIST_DIRECTORIES false "${OUTDIR}/gmon.*")
if(NOT _gprof_gmon_files)
    message(FATAL_ERROR "gprof_analysis: no gmon.* files found in ${OUTDIR}")
    return()
endif()
foreach(_gprof_gmon IN LISTS _gprof_gmon_files)
    get_filename_component(_gprof_gmon_name "${_gprof_gmon}" NAME)
    set(_gprof_report "${OUTDIR}/${_gprof_gmon_name}.gprof_output.txt")
    execute_process(
        COMMAND gprof "${EXE}" "${_gprof_gmon}"
        OUTPUT_VARIABLE _gprof_out
        ERROR_VARIABLE  _gprof_err
        RESULT_VARIABLE _gprof_rc
    )
    if(_gprof_rc)
        message(FATAL_ERROR "gprof exited with code ${_gprof_rc}: ${_gprof_err}")
    else()
        file(WRITE "${_gprof_report}" "${_gprof_out}")
    endif()
endforeach()
]=])
endif()

# Write the vtune post-processing script once into the output directory.
# It is invoked at test time via: cmake -DRESULTDIR=<dir> -P <script>
if(PROFILING_TOOL STREQUAL "vtune" AND PROFILING_ANALYSIS)
    file(WRITE "${PROFILING_OUTPUT_DIR}/run_vtune_analysis.cmake" [=[
# run_vtune_analysis.cmake — generated by Profiling.cmake
# Parameters (via -D): RESULTDIR  path to the per-test vtune-result directory
execute_process(
    COMMAND vtune -report hotspots
        -result-dir "${RESULTDIR}"
        -format text
        -report-output "${RESULTDIR}/hotspots.txt"
    OUTPUT_VARIABLE _vtune_out
    ERROR_VARIABLE  _vtune_err
    RESULT_VARIABLE _vtune_rc
)
if(_vtune_rc)
    message(FATAL_ERROR "vtune -report exited with code ${_vtune_rc}: ${_vtune_err}")
endif()
]=])
endif()

# Write the HPCToolkit post-processing script once into the output directory.
# It is invoked at test time via: cmake -DEXE=<path> -DOUTDIR=<dir> -P <script>
if(PROFILING_TOOL STREQUAL "hpctoolkit" AND PROFILING_ANALYSIS)
    file(WRITE "${PROFILING_OUTPUT_DIR}/run_hpctoolkit_analysis.cmake" [=[
# run_hpctoolkit_analysis.cmake — generated by Profiling.cmake
# Parameters (via -D): EXE     absolute path to the instrumented executable
#                      OUTDIR  per-test profiling output directory
#                              (contains measurements/ subdir written by hpcrun)

# 1. hpcstruct: parse the binary's DWARF debug info and write a struct file.
#    -o expects a file path, not a directory.
set(_hpct_structs_dir "${OUTDIR}/structs")
file(MAKE_DIRECTORY "${_hpct_structs_dir}")
get_filename_component(_hpct_exe_name "${EXE}" NAME)
set(_hpct_struct_file "${_hpct_structs_dir}/${_hpct_exe_name}.hpcstruct")
execute_process(
    COMMAND hpcstruct -o "${_hpct_struct_file}" "${EXE}"
    OUTPUT_VARIABLE _hpct_out
    ERROR_VARIABLE  _hpct_err
    RESULT_VARIABLE _hpct_rc
)
if(_hpct_rc)
    message(FATAL_ERROR "hpcstruct exited with code ${_hpct_rc}: ${_hpct_err}")
endif()

# 2. hpcprof: correlate measurements with struct info, produce a viewable database.
execute_process(
    COMMAND hpcprof
        -S "${_hpct_struct_file}"
        -o "${OUTDIR}/hpctoolkit-database"
        "${OUTDIR}/measurements"
    OUTPUT_VARIABLE _hpct_out
    ERROR_VARIABLE  _hpct_err
    RESULT_VARIABLE _hpct_rc
)
if(_hpct_rc)
    message(FATAL_ERROR "hpcprof exited with code ${_hpct_rc}: ${_hpct_err}")
endif()
]=])
endif()
#
# Overrides CMake's built-in add_test().  Supports the new-form calling
# convention only:
#   add_test(NAME <name> COMMAND <exe> [args…] [WORKING_DIRECTORY <dir>])
#
# For gprof the test is registered unchanged and GMON_OUT_PREFIX is set via
# the ENVIRONMENT test property so glibc writes gmon.<pid> into the per-test
# output directory instead of the working directory.
#
# For hpctoolkit and vtune the profiler binary is prepended to COMMAND.
# -----------------------------------------------------------------------------
function(add_test)

    cmake_parse_arguments(PARSE_ARGV 0 _PROF_AT
        "COMMAND_EXPAND_LISTS"
        "NAME;WORKING_DIRECTORY"
        "COMMAND;CONFIGURATIONS"
    )

    # ── Per-test output directory ─────────────────────────────────────────
    string(MAKE_C_IDENTIFIER "${_PROF_AT_NAME}" _prof_test_id)
    set(_prof_outdir "${PROFILING_OUTPUT_DIR}/${_prof_test_id}")
    file(MAKE_DIRECTORY "${_prof_outdir}")

    if(PROFILING_TOOL STREQUAL "gprof")
        # Register the test unchanged; set GMON_OUT_PREFIX so glibc writes
        # gmon.<pid> into the per-test directory instead of the working dir.
        _add_test(${ARGV})
        set_tests_properties("${_PROF_AT_NAME}" PROPERTIES
            ENVIRONMENT "GMON_OUT_PREFIX=${_prof_outdir}/gmon")

        if(PROFILING_ANALYSIS)
            # Resolve the executable: support both CMake target names and plain paths.
            list(GET _PROF_AT_COMMAND 0 _prof_exe)
            if(TARGET "${_prof_exe}")
                set(_prof_exe_arg "$<TARGET_FILE:${_prof_exe}>")
            else()
                set(_prof_exe_arg "${_prof_exe}")
            endif()

            _add_test(NAME "${_PROF_AT_NAME}_gprof_analysis"
                COMMAND "${CMAKE_COMMAND}"
                    "-DEXE=${_prof_exe_arg}"
                    "-DOUTDIR=${_prof_outdir}"
                    -P "${PROFILING_OUTPUT_DIR}/run_gprof_analysis.cmake")
            # DEPENDS guarantees the analysis test is scheduled after the main
            # test has run and written its gmon.* files.
            set_tests_properties("${_PROF_AT_NAME}_gprof_analysis" PROPERTIES
                DEPENDS "${_PROF_AT_NAME}")

            unset(_prof_exe)
            unset(_prof_exe_arg)
        endif()

    elseif(PROFILING_TOOL STREQUAL "hpctoolkit")
        # Prepend hpcrun; raw measurements land in <outdir>/measurements/.
        file(MAKE_DIRECTORY "${_prof_outdir}/measurements")
        set(_prof_fwd_args NAME "${_PROF_AT_NAME}"
            COMMAND hpcrun -o "${_prof_outdir}/measurements" ${CMAKE_BINARY_DIR}/${_PROF_AT_COMMAND})
        if(_PROF_AT_WORKING_DIRECTORY)
            list(APPEND _prof_fwd_args WORKING_DIRECTORY "${_PROF_AT_WORKING_DIRECTORY}")
        endif()
        _add_test(${_prof_fwd_args})
        unset(_prof_fwd_args)

        if(PROFILING_ANALYSIS)
            # Resolve the executable: support both CMake target names and plain paths.
            list(GET _PROF_AT_COMMAND 0 _prof_exe)
            if(TARGET "${_prof_exe}")
                set(_prof_exe_arg "$<TARGET_FILE:${_prof_exe}>")
            else()
                set(_prof_exe_arg "${_prof_exe}")
            endif()

            _add_test(NAME "${_PROF_AT_NAME}_hpctoolkit_analysis"
                COMMAND "${CMAKE_COMMAND}"
                    "-DEXE=${_prof_exe_arg}"
                    "-DOUTDIR=${_prof_outdir}"
                    -P "${PROFILING_OUTPUT_DIR}/run_hpctoolkit_analysis.cmake")
            # DEPENDS guarantees the analysis test runs after hpcrun has written
            # its measurements/ directory.
            set_tests_properties("${_PROF_AT_NAME}_hpctoolkit_analysis" PROPERTIES
                DEPENDS "${_PROF_AT_NAME}")

            unset(_prof_exe)
            unset(_prof_exe_arg)
        endif()

    elseif(PROFILING_TOOL STREQUAL "vtune")
        # Prepend vtune; results land in <outdir>/vtune-result/.
        set(_prof_fwd_args NAME "${_PROF_AT_NAME}"
            COMMAND vtune
                -collect hotspots
                -allow-multiple-runs
                -result-dir "${_prof_outdir}/vtune-result"
                --
                ${CMAKE_BINARY_DIR}/${_PROF_AT_COMMAND})
        if(_PROF_AT_WORKING_DIRECTORY)
            list(APPEND _prof_fwd_args WORKING_DIRECTORY "${_PROF_AT_WORKING_DIRECTORY}")
        endif()
        _add_test(${_prof_fwd_args})
        unset(_prof_fwd_args)

        if(PROFILING_ANALYSIS)
            _add_test(NAME "${_PROF_AT_NAME}_vtune_analysis"
                COMMAND "${CMAKE_COMMAND}"
                    "-DRESULTDIR=${_prof_outdir}/vtune-result"
                    -P "${PROFILING_OUTPUT_DIR}/run_vtune_analysis.cmake")
            set_tests_properties("${_PROF_AT_NAME}_vtune_analysis" PROPERTIES
                DEPENDS "${_PROF_AT_NAME}")
        endif()

    endif()

    unset(_prof_test_id)
    unset(_prof_outdir)
    unset(_PROF_AT_NAME)
    unset(_PROF_AT_COMMAND)
    unset(_PROF_AT_WORKING_DIRECTORY)
    unset(_PROF_AT_CONFIGURATIONS)
    unset(_PROF_AT_COMMAND_EXPAND_LISTS)
    unset(_PROF_AT_UNPARSED_ARGUMENTS)

endfunction() # add_test

message(STATUS
    "Profiling.cmake: profiling ENABLED "
    "(tool=${PROFILING_TOOL}, output=${PROFILING_OUTPUT_DIR})")
